import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { randomUUID } from 'node:crypto'
import { DateTime } from 'luxon'
import db from '@adonisjs/lucid/services/db'

// ─── IDs fixes pour cohérence entre tables ────────────────────────────────────

const USERS = {
  thomas: randomUUID(),
  alice: randomUUID(),
  marc: randomUUID(),
  julie: randomUUID(),
  pierre: randomUUID(),
  sophie: randomUUID(),
  lucas: randomUUID(),
  emma: randomUUID(),
}

const EVENTS = {
  daftpunk: 'tm_3000001',
  stromae: 'tm_3000002',
  coldplay: 'tm_3000003',
  rockenseine: 'tm_3000004',
  pnl: 'tm_3000005',
}

const RIDES = {
  r1: randomUUID(),
  r2: randomUUID(),
  r3: randomUUID(),
  r4: randomUUID(),
  r5: randomUUID(),
  r6: randomUUID(),
  r7: randomUUID(),
  r8: randomUUID(),
  r9: randomUUID(),
  r10: randomUUID(),
}

const BOOKINGS = {
  b1: randomUUID(),
  b2: randomUUID(),
  b3: randomUUID(),
  b4: randomUUID(),
  b5: randomUUID(),
  b6: randomUUID(),
  b7: randomUUID(),
  b8: randomUUID(),
}

// ─── Seeder ───────────────────────────────────────────────────────────────────

export default class extends BaseSeeder {
  async run() {
    console.log('🌱 Seeding GoConcert mock data...')

    await this.seedUsers()
    await this.seedEvents()
    await this.seedRides()
    await this.seedBookings()
    await this.seedAlerts()
    await this.seedReviews()

    console.log('✅ Seeding terminé !')
  }

  // ─── Utilisateurs ───────────────────────────────────────────────────────────

  private async seedUsers() {
    console.log('  → Users...')
    await db.table('users').multiInsert([
      {
        id: USERS.thomas,
        full_name: 'Thomas Dupont',
        email: 'thomas.dupont@gmail.com',
        phone: null,
        auth_provider: 'GOOGLE',
        provider_id: 'google_thomas_001',
        avatar_url: 'https://api.dicebear.com/8.x/initials/svg?seed=TD',
        birth_date: DateTime.fromISO('1995-03-14').toSQL(),
        bio: 'Ponctuel, musicophile et grand fan de concerts. Je fais Paris ↔ province régulièrement.',
        car_model: 'Peugeot 308',
        push_token: null,
        platform: null,
        rating_as_driver: 4.8,
        rating_as_passenger: 4.9,
        rides_as_driver_count: 34,
        rides_as_passenger_count: 12,
        created_at: DateTime.now().minus({ months: 14 }).toSQL(),
        updated_at: DateTime.now().toSQL(),
      },
      {
        id: USERS.alice,
        full_name: 'Alice Martin',
        email: 'alice.martin@gmail.com',
        phone: null,
        auth_provider: 'GOOGLE',
        provider_id: 'google_alice_002',
        avatar_url: 'https://api.dicebear.com/8.x/initials/svg?seed=AM',
        birth_date: DateTime.fromISO('1992-07-22').toSQL(),
        bio: "J'adore les festivals ! Je partage souvent mes trajets pour les concerts parisiens.",
        car_model: 'Renault Clio',
        push_token: null,
        platform: null,
        rating_as_driver: 4.9,
        rating_as_passenger: 5.0,
        rides_as_driver_count: 21,
        rides_as_passenger_count: 8,
        created_at: DateTime.now().minus({ months: 18 }).toSQL(),
        updated_at: DateTime.now().toSQL(),
      },
      {
        id: USERS.marc,
        full_name: 'Marc Lefebvre',
        email: 'marc.lefebvre@icloud.com',
        phone: null,
        auth_provider: 'APPLE',
        provider_id: 'apple_marc_003',
        avatar_url: 'https://api.dicebear.com/8.x/initials/svg?seed=ML',
        birth_date: DateTime.fromISO('1988-11-05').toSQL(),
        bio: 'Conducteur expérimenté, véhicule spacieux. Coffre large pour les instruments !',
        car_model: 'Volkswagen Passat',
        push_token: null,
        platform: null,
        rating_as_driver: 4.6,
        rating_as_passenger: 4.7,
        rides_as_driver_count: 48,
        rides_as_passenger_count: 3,
        created_at: DateTime.now().minus({ months: 24 }).toSQL(),
        updated_at: DateTime.now().toSQL(),
      },
      {
        id: USERS.julie,
        full_name: 'Julie Rousseau',
        email: null,
        phone: '+33612345678',
        auth_provider: 'PHONE_OTP',
        provider_id: '+33612345678',
        avatar_url: 'https://api.dicebear.com/8.x/initials/svg?seed=JR',
        birth_date: DateTime.fromISO('1998-04-30').toSQL(),
        bio: null,
        car_model: null,
        push_token: 'ExponentPushToken[julie_mock_token_001]',
        platform: 'ios',
        rating_as_driver: 0,
        rating_as_passenger: 4.5,
        rides_as_driver_count: 0,
        rides_as_passenger_count: 7,
        created_at: DateTime.now().minus({ months: 6 }).toSQL(),
        updated_at: DateTime.now().toSQL(),
      },
      {
        id: USERS.pierre,
        full_name: 'Pierre Kante',
        email: 'pierre.kante@gmail.com',
        phone: null,
        auth_provider: 'GOOGLE',
        provider_id: 'google_pierre_005',
        avatar_url: 'https://api.dicebear.com/8.x/initials/svg?seed=PK',
        birth_date: DateTime.fromISO('1993-09-12').toSQL(),
        bio: 'Fan de musique électro et rap. Je propose des trajets chaque été pour les festivals.',
        car_model: 'Citroën C4',
        push_token: null,
        platform: null,
        rating_as_driver: 4.7,
        rating_as_passenger: 4.8,
        rides_as_driver_count: 16,
        rides_as_passenger_count: 11,
        created_at: DateTime.now().minus({ months: 10 }).toSQL(),
        updated_at: DateTime.now().toSQL(),
      },
      {
        id: USERS.sophie,
        full_name: 'Sophie Bernard',
        email: null,
        phone: '+33698765432',
        auth_provider: 'PHONE_OTP',
        provider_id: '+33698765432',
        avatar_url: 'https://api.dicebear.com/8.x/initials/svg?seed=SB',
        birth_date: DateTime.fromISO('2000-01-15').toSQL(),
        bio: null,
        car_model: null,
        push_token: 'ExponentPushToken[sophie_mock_token_002]',
        platform: 'android',
        rating_as_driver: 0,
        rating_as_passenger: 4.3,
        rides_as_driver_count: 0,
        rides_as_passenger_count: 4,
        created_at: DateTime.now().minus({ months: 3 }).toSQL(),
        updated_at: DateTime.now().toSQL(),
      },
      {
        id: USERS.lucas,
        full_name: 'Lucas Faure',
        email: 'lucas.faure@icloud.com',
        phone: null,
        auth_provider: 'APPLE',
        provider_id: 'apple_lucas_007',
        avatar_url: 'https://api.dicebear.com/8.x/initials/svg?seed=LF',
        birth_date: DateTime.fromISO('1990-06-08').toSQL(),
        bio: 'Amateur de rock et de métal. Trajet souvent depuis Versailles ou Issy-les-Moulineaux.',
        car_model: 'Ford Focus',
        push_token: null,
        platform: null,
        rating_as_driver: 4.5,
        rating_as_passenger: 4.6,
        rides_as_driver_count: 9,
        rides_as_passenger_count: 6,
        created_at: DateTime.now().minus({ months: 8 }).toSQL(),
        updated_at: DateTime.now().toSQL(),
      },
      {
        id: USERS.emma,
        full_name: 'Emma Tanguy',
        email: 'emma.tanguy@gmail.com',
        phone: null,
        auth_provider: 'GOOGLE',
        provider_id: 'google_emma_008',
        avatar_url: 'https://api.dicebear.com/8.x/initials/svg?seed=ET',
        birth_date: DateTime.fromISO('1997-12-20').toSQL(),
        bio: null,
        car_model: null,
        push_token: 'ExponentPushToken[emma_mock_token_003]',
        platform: 'ios',
        rating_as_driver: 0,
        rating_as_passenger: 5.0,
        rides_as_driver_count: 0,
        rides_as_passenger_count: 15,
        created_at: DateTime.now().minus({ months: 20 }).toSQL(),
        updated_at: DateTime.now().toSQL(),
      },
    ])
  }

  // ─── Événements ─────────────────────────────────────────────────────────────

  private async seedEvents() {
    console.log('  → Events...')
    await db.table('events').multiInsert([
      {
        id: EVENTS.daftpunk,
        ticketmaster_id: '3000001',
        name: 'Daft Punk Reunion Tour',
        venue_name: 'Stade de France',
        venue_address: 'Rue Francis de Pressensé, 93210 Saint-Denis',
        city: 'Paris',
        country: 'FR',
        latitude: 48.9244,
        longitude: 2.3601,
        starts_at: DateTime.fromISO('2026-06-27T20:00:00').toSQL(),
        image_url: 'https://via.placeholder.com/400x200/1a1a2e/ffffff?text=Daft+Punk',
        genre: 'Electronic',
        url: 'https://www.ticketmaster.fr/manifestation/3000001',
        cached_at: DateTime.now().toSQL(),
      },
      {
        id: EVENTS.stromae,
        ticketmaster_id: '3000002',
        name: 'Stromae — Multitude Tour',
        venue_name: 'Accor Arena',
        venue_address: '8 Bd de Bercy, 75012 Paris',
        city: 'Paris',
        country: 'FR',
        latitude: 48.8384,
        longitude: 2.3789,
        starts_at: DateTime.fromISO('2026-07-12T20:30:00').toSQL(),
        image_url: 'https://via.placeholder.com/400x200/2d2d2d/ffffff?text=Stromae',
        genre: 'Pop',
        url: 'https://www.ticketmaster.fr/manifestation/3000002',
        cached_at: DateTime.now().toSQL(),
      },
      {
        id: EVENTS.coldplay,
        ticketmaster_id: '3000003',
        name: 'Coldplay — Music of the Spheres',
        venue_name: 'Stade de France',
        venue_address: 'Rue Francis de Pressensé, 93210 Saint-Denis',
        city: 'Paris',
        country: 'FR',
        latitude: 48.9244,
        longitude: 2.3601,
        starts_at: DateTime.fromISO('2026-09-05T19:00:00').toSQL(),
        image_url: 'https://via.placeholder.com/400x200/0d47a1/ffffff?text=Coldplay',
        genre: 'Rock',
        url: 'https://www.ticketmaster.fr/manifestation/3000003',
        cached_at: DateTime.now().toSQL(),
      },
      {
        id: EVENTS.rockenseine,
        ticketmaster_id: '3000004',
        name: 'Rock en Seine 2026',
        venue_name: 'Domaine National de Saint-Cloud',
        venue_address: 'Domaine National, 92210 Saint-Cloud',
        city: 'Saint-Cloud',
        country: 'FR',
        latitude: 48.8467,
        longitude: 2.2,
        starts_at: DateTime.fromISO('2026-08-28T14:00:00').toSQL(),
        image_url: 'https://via.placeholder.com/400x200/4a148c/ffffff?text=Rock+en+Seine',
        genre: 'Festival',
        url: 'https://www.ticketmaster.fr/manifestation/3000004',
        cached_at: DateTime.now().toSQL(),
      },
      {
        id: EVENTS.pnl,
        ticketmaster_id: '3000005',
        name: 'PNL — Le Monde Chico Tour',
        venue_name: 'Parc des Princes',
        venue_address: '24 Rue du Commandant Guilbaud, 75016 Paris',
        city: 'Paris',
        country: 'FR',
        latitude: 48.8414,
        longitude: 2.2531,
        starts_at: DateTime.fromISO('2026-08-01T21:00:00').toSQL(),
        image_url: 'https://via.placeholder.com/400x200/212121/ffffff?text=PNL',
        genre: 'Rap',
        url: 'https://www.ticketmaster.fr/manifestation/3000005',
        cached_at: DateTime.now().toSQL(),
      },
    ])
  }

  // ─── Trajets ────────────────────────────────────────────────────────────────

  private async seedRides() {
    console.log('  → Rides...')
    await db.table('rides').multiInsert([
      // ── Daft Punk ──
      {
        id: RIDES.r1,
        driver_id: USERS.thomas,
        event_id: EVENTS.daftpunk,
        direction: 'OUTBOUND',
        departure_lat: 48.832,
        departure_lng: 2.289,
        departure_address: 'Porte de Versailles, Paris 15e',
        departure_time: DateTime.fromISO('2026-06-27T17:30:00').toSQL(),
        estimated_arrival: DateTime.fromISO('2026-06-27T19:00:00').toSQL(),
        total_seats: 3,
        available_seats: 2,
        price_per_seat: 8.5,
        min_price: 7.0,
        max_price: 12.0,
        constraints: JSON.stringify(['NO_SMOKING', 'NO_PETS']),
        notes: 'Coffre un peu petit, préférez les petits sacs.',
        status: 'ACTIVE',
        created_at: DateTime.now().minus({ days: 5 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 5 }).toSQL(),
      },
      {
        id: RIDES.r2,
        driver_id: USERS.alice,
        event_id: EVENTS.daftpunk,
        direction: 'OUTBOUND',
        departure_lat: 48.8534,
        departure_lng: 2.3488,
        departure_address: 'Opéra, Paris 9e',
        departure_time: DateTime.fromISO('2026-06-27T18:00:00').toSQL(),
        estimated_arrival: DateTime.fromISO('2026-06-27T19:15:00').toSQL(),
        total_seats: 4,
        available_seats: 3,
        price_per_seat: 7.0,
        min_price: 6.0,
        max_price: 10.0,
        constraints: JSON.stringify(['NO_FOOD']),
        notes: null,
        status: 'ACTIVE',
        created_at: DateTime.now().minus({ days: 4 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 4 }).toSQL(),
      },
      {
        id: RIDES.r3,
        driver_id: USERS.thomas,
        event_id: EVENTS.daftpunk,
        direction: 'RETURN',
        departure_lat: 48.9244,
        departure_lng: 2.3601,
        departure_address: 'Stade de France — Sortie Nord',
        departure_time: DateTime.fromISO('2026-06-27T23:30:00').toSQL(),
        estimated_arrival: DateTime.fromISO('2026-06-28T00:45:00').toSQL(),
        total_seats: 3,
        available_seats: 3,
        price_per_seat: 8.5,
        min_price: 7.0,
        max_price: 12.0,
        constraints: JSON.stringify(['NO_SMOKING']),
        notes: 'Départ 15 min après la fin du concert.',
        status: 'ACTIVE',
        created_at: DateTime.now().minus({ days: 5 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 5 }).toSQL(),
      },
      // ── Stromae ──
      {
        id: RIDES.r4,
        driver_id: USERS.marc,
        event_id: EVENTS.stromae,
        direction: 'OUTBOUND',
        departure_lat: 48.8798,
        departure_lng: 2.3553,
        departure_address: 'Gare du Nord, Paris 10e',
        departure_time: DateTime.fromISO('2026-07-12T19:00:00').toSQL(),
        estimated_arrival: DateTime.fromISO('2026-07-12T20:00:00').toSQL(),
        total_seats: 4,
        available_seats: 4,
        price_per_seat: 6.0,
        min_price: 5.0,
        max_price: 9.0,
        constraints: JSON.stringify([]),
        notes: 'Grand coffre, lugages bienvenus.',
        status: 'ACTIVE',
        created_at: DateTime.now().minus({ days: 10 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 10 }).toSQL(),
      },
      {
        id: RIDES.r5,
        driver_id: USERS.pierre,
        event_id: EVENTS.stromae,
        direction: 'OUTBOUND',
        departure_lat: 48.8149,
        departure_lng: 2.3635,
        departure_address: 'Place d\'Italie, Paris 13e',
        departure_time: DateTime.fromISO('2026-07-12T19:30:00').toSQL(),
        estimated_arrival: DateTime.fromISO('2026-07-12T20:15:00').toSQL(),
        total_seats: 3,
        available_seats: 1,
        price_per_seat: 5.5,
        min_price: 4.5,
        max_price: 8.0,
        constraints: JSON.stringify(['NO_SMOKING', 'NO_FOOD']),
        notes: null,
        status: 'ACTIVE',
        created_at: DateTime.now().minus({ days: 8 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 8 }).toSQL(),
      },
      // ── Rock en Seine ──
      {
        id: RIDES.r6,
        driver_id: USERS.lucas,
        event_id: EVENTS.rockenseine,
        direction: 'OUTBOUND',
        departure_lat: 48.8566,
        departure_lng: 2.3522,
        departure_address: 'Centre de Paris — Place de la République',
        departure_time: DateTime.fromISO('2026-08-28T12:00:00').toSQL(),
        estimated_arrival: DateTime.fromISO('2026-08-28T13:30:00').toSQL(),
        total_seats: 4,
        available_seats: 4,
        price_per_seat: 9.0,
        min_price: 7.5,
        max_price: 13.0,
        constraints: JSON.stringify(['NO_PETS']),
        notes: 'On peut s\'arrêter en chemin pour déjeuner si vous voulez.',
        status: 'ACTIVE',
        created_at: DateTime.now().minus({ days: 15 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 15 }).toSQL(),
      },
      {
        id: RIDES.r7,
        driver_id: USERS.alice,
        event_id: EVENTS.rockenseine,
        direction: 'OUTBOUND',
        departure_lat: 48.8467,
        departure_lng: 2.3104,
        departure_address: 'Trocadéro, Paris 16e',
        departure_time: DateTime.fromISO('2026-08-28T13:00:00').toSQL(),
        estimated_arrival: DateTime.fromISO('2026-08-28T13:45:00').toSQL(),
        total_seats: 3,
        available_seats: 2,
        price_per_seat: 7.0,
        min_price: 5.5,
        max_price: 10.0,
        constraints: JSON.stringify(['NO_SMOKING']),
        notes: null,
        status: 'ACTIVE',
        created_at: DateTime.now().minus({ days: 12 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 12 }).toSQL(),
      },
      // ── PNL ──
      {
        id: RIDES.r8,
        driver_id: USERS.pierre,
        event_id: EVENTS.pnl,
        direction: 'OUTBOUND',
        departure_lat: 48.8534,
        departure_lng: 2.3488,
        departure_address: 'Châtelet, Paris 1er',
        departure_time: DateTime.fromISO('2026-08-01T19:30:00').toSQL(),
        estimated_arrival: DateTime.fromISO('2026-08-01T20:30:00').toSQL(),
        total_seats: 4,
        available_seats: 4,
        price_per_seat: 7.5,
        min_price: 6.0,
        max_price: 11.0,
        constraints: JSON.stringify([]),
        notes: 'Ambiance garantie !',
        status: 'ACTIVE',
        created_at: DateTime.now().minus({ days: 7 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 7 }).toSQL(),
      },
      // ── Trajets passés (status COMPLETED, pour les reviews) ──
      {
        id: RIDES.r9,
        driver_id: USERS.thomas,
        event_id: EVENTS.coldplay,
        direction: 'OUTBOUND',
        departure_lat: 48.832,
        departure_lng: 2.289,
        departure_address: 'Porte de Versailles, Paris 15e',
        departure_time: DateTime.fromISO('2026-03-10T17:00:00').toSQL(),
        estimated_arrival: DateTime.fromISO('2026-03-10T18:30:00').toSQL(),
        total_seats: 3,
        available_seats: 0,
        price_per_seat: 8.0,
        min_price: 6.5,
        max_price: 11.0,
        constraints: JSON.stringify(['NO_SMOKING']),
        notes: null,
        status: 'COMPLETED',
        created_at: DateTime.now().minus({ months: 2 }).toSQL(),
        updated_at: DateTime.now().minus({ months: 1 }).toSQL(),
      },
      {
        id: RIDES.r10,
        driver_id: USERS.marc,
        event_id: EVENTS.stromae,
        direction: 'OUTBOUND',
        departure_lat: 48.8798,
        departure_lng: 2.3553,
        departure_address: 'Gare du Nord, Paris 10e',
        departure_time: DateTime.fromISO('2026-02-20T19:30:00').toSQL(),
        estimated_arrival: DateTime.fromISO('2026-02-20T20:30:00').toSQL(),
        total_seats: 4,
        available_seats: 0,
        price_per_seat: 6.0,
        min_price: 5.0,
        max_price: 9.0,
        constraints: JSON.stringify([]),
        notes: null,
        status: 'COMPLETED',
        created_at: DateTime.now().minus({ months: 3 }).toSQL(),
        updated_at: DateTime.now().minus({ months: 2 }).toSQL(),
      },
    ])
  }

  // ─── Réservations ───────────────────────────────────────────────────────────

  private async seedBookings() {
    console.log('  → Bookings...')
    await db.table('bookings').multiInsert([
      // Réservation active — Julie sur trajet Thomas/Daft Punk aller
      {
        id: BOOKINGS.b1,
        passenger_id: USERS.julie,
        ride_id: RIDES.r1,
        seats_booked: 1,
        total_price: 8.5,
        commission: 0.85,
        status: 'CONFIRMED',
        payment_intent_id: null,
        payment_status: 'UNPAID',
        cancelled_by: null,
        cancelled_at: null,
        cancel_reason: null,
        created_at: DateTime.now().minus({ days: 3 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 3 }).toSQL(),
      },
      // Réservation active — Sophie sur trajet Alice/Daft Punk aller
      {
        id: BOOKINGS.b2,
        passenger_id: USERS.sophie,
        ride_id: RIDES.r2,
        seats_booked: 1,
        total_price: 7.0,
        commission: 0.7,
        status: 'CONFIRMED',
        payment_intent_id: null,
        payment_status: 'UNPAID',
        cancelled_by: null,
        cancelled_at: null,
        cancel_reason: null,
        created_at: DateTime.now().minus({ days: 2 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 2 }).toSQL(),
      },
      // Réservation 2 places — Emma sur trajet Marc/Stromae
      {
        id: BOOKINGS.b3,
        passenger_id: USERS.emma,
        ride_id: RIDES.r4,
        seats_booked: 2,
        total_price: 12.0,
        commission: 1.2,
        status: 'CONFIRMED',
        payment_intent_id: null,
        payment_status: 'UNPAID',
        cancelled_by: null,
        cancelled_at: null,
        cancel_reason: null,
        created_at: DateTime.now().minus({ days: 6 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 6 }).toSQL(),
      },
      // Réservation — Julie sur trajet Pierre/Stromae (1 place restante)
      {
        id: BOOKINGS.b4,
        passenger_id: USERS.julie,
        ride_id: RIDES.r5,
        seats_booked: 2,
        total_price: 11.0,
        commission: 1.1,
        status: 'CONFIRMED',
        payment_intent_id: null,
        payment_status: 'UNPAID',
        cancelled_by: null,
        cancelled_at: null,
        cancel_reason: null,
        created_at: DateTime.now().minus({ days: 5 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 5 }).toSQL(),
      },
      // Réservation annulée — Sophie sur trajet Lucas/Rock en Seine
      {
        id: BOOKINGS.b5,
        passenger_id: USERS.sophie,
        ride_id: RIDES.r6,
        seats_booked: 1,
        total_price: 9.0,
        commission: 0.9,
        status: 'CANCELLED',
        payment_intent_id: null,
        payment_status: 'UNPAID',
        cancelled_by: USERS.sophie,
        cancelled_at: DateTime.now().minus({ days: 10 }).toSQL(),
        cancel_reason: 'Je ne peux finalement pas venir.',
        created_at: DateTime.now().minus({ days: 13 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 10 }).toSQL(),
      },
      // ── Réservations terminées (pour les reviews) ──
      {
        id: BOOKINGS.b6,
        passenger_id: USERS.julie,
        ride_id: RIDES.r9,
        seats_booked: 1,
        total_price: 8.0,
        commission: 0.8,
        status: 'COMPLETED',
        payment_intent_id: null,
        payment_status: 'UNPAID',
        cancelled_by: null,
        cancelled_at: null,
        cancel_reason: null,
        created_at: DateTime.now().minus({ months: 2 }).toSQL(),
        updated_at: DateTime.now().minus({ months: 1 }).toSQL(),
      },
      {
        id: BOOKINGS.b7,
        passenger_id: USERS.emma,
        ride_id: RIDES.r9,
        seats_booked: 1,
        total_price: 8.0,
        commission: 0.8,
        status: 'COMPLETED',
        payment_intent_id: null,
        payment_status: 'UNPAID',
        cancelled_by: null,
        cancelled_at: null,
        cancel_reason: null,
        created_at: DateTime.now().minus({ months: 2 }).toSQL(),
        updated_at: DateTime.now().minus({ months: 1 }).toSQL(),
      },
      {
        id: BOOKINGS.b8,
        passenger_id: USERS.sophie,
        ride_id: RIDES.r10,
        seats_booked: 2,
        total_price: 12.0,
        commission: 1.2,
        status: 'COMPLETED',
        payment_intent_id: null,
        payment_status: 'UNPAID',
        cancelled_by: null,
        cancelled_at: null,
        cancel_reason: null,
        created_at: DateTime.now().minus({ months: 3 }).toSQL(),
        updated_at: DateTime.now().minus({ months: 2 }).toSQL(),
      },
    ])
  }

  // ─── Alertes ────────────────────────────────────────────────────────────────

  private async seedAlerts() {
    console.log('  → Alerts...')
    await db.table('alerts').multiInsert([
      // Emma cherche un trajet aller pour Rock en Seine depuis Paris centre
      {
        id: randomUUID(),
        user_id: USERS.emma,
        event_id: EVENTS.rockenseine,
        origin_lat: 48.8534,
        origin_lng: 2.3488,
        radius_km: 15,
        direction: 'OUTBOUND',
        is_active: true,
        triggered_at: null,
        created_at: DateTime.now().minus({ days: 10 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 10 }).toSQL(),
      },
      // Sophie cherche un trajet aller PNL depuis la Rive Droite
      {
        id: randomUUID(),
        user_id: USERS.sophie,
        event_id: EVENTS.pnl,
        origin_lat: 48.8698,
        origin_lng: 2.3078,
        radius_km: 10,
        direction: 'OUTBOUND',
        is_active: true,
        triggered_at: null,
        created_at: DateTime.now().minus({ days: 5 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 5 }).toSQL(),
      },
      // Julie cherche un trajet retour Coldplay
      {
        id: randomUUID(),
        user_id: USERS.julie,
        event_id: EVENTS.coldplay,
        origin_lat: 48.832,
        origin_lng: 2.289,
        radius_km: 20,
        direction: 'RETURN',
        is_active: true,
        triggered_at: null,
        created_at: DateTime.now().minus({ days: 3 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 3 }).toSQL(),
      },
      // Emma cherche un trajet aller Stromae (déjà déclenchée une fois)
      {
        id: randomUUID(),
        user_id: USERS.emma,
        event_id: EVENTS.stromae,
        origin_lat: 48.8566,
        origin_lng: 2.3522,
        radius_km: 12,
        direction: 'OUTBOUND',
        is_active: true,
        triggered_at: DateTime.now().minus({ days: 7 }).toSQL(),
        created_at: DateTime.now().minus({ days: 9 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 7 }).toSQL(),
      },
      // Thomas cherche un retour Daft Punk (inactive)
      {
        id: randomUUID(),
        user_id: USERS.thomas,
        event_id: EVENTS.daftpunk,
        origin_lat: 48.832,
        origin_lng: 2.289,
        radius_km: 5,
        direction: 'RETURN',
        is_active: false,
        triggered_at: null,
        created_at: DateTime.now().minus({ days: 20 }).toSQL(),
        updated_at: DateTime.now().minus({ days: 15 }).toSQL(),
      },
    ])
  }

  // ─── Avis ───────────────────────────────────────────────────────────────────

  private async seedReviews() {
    console.log('  → Reviews...')
    await db.table('reviews').multiInsert([
      // Julie note Thomas (Coldplay ride) — passager → conducteur
      {
        id: randomUUID(),
        booking_id: BOOKINGS.b6,
        author_id: USERS.julie,
        target_id: USERS.thomas,
        role: 'PASSENGER_REVIEWING_DRIVER',
        rating: 5,
        comment: 'Très ponctuel, voiture propre, excellente ambiance musicale en route !',
        created_at: DateTime.now().minus({ weeks: 3 }).toSQL(),
      },
      // Thomas note Julie — conducteur → passager
      {
        id: randomUUID(),
        booking_id: BOOKINGS.b6,
        author_id: USERS.thomas,
        target_id: USERS.julie,
        role: 'DRIVER_REVIEWING_PASSENGER',
        rating: 5,
        comment: 'Passagère parfaite, à l\'heure et très sympa.',
        created_at: DateTime.now().minus({ weeks: 3 }).toSQL(),
      },
      // Emma note Thomas (Coldplay ride)
      {
        id: randomUUID(),
        booking_id: BOOKINGS.b7,
        author_id: USERS.emma,
        target_id: USERS.thomas,
        role: 'PASSENGER_REVIEWING_DRIVER',
        rating: 5,
        comment: 'Top conducteur, arrivée en avance au concert. Je recommande !',
        created_at: DateTime.now().minus({ weeks: 3 }).toSQL(),
      },
      // Thomas note Emma
      {
        id: randomUUID(),
        booking_id: BOOKINGS.b7,
        author_id: USERS.thomas,
        target_id: USERS.emma,
        role: 'DRIVER_REVIEWING_PASSENGER',
        rating: 5,
        comment: null,
        created_at: DateTime.now().minus({ weeks: 3 }).toSQL(),
      },
      // Sophie note Marc (Stromae ride)
      {
        id: randomUUID(),
        booking_id: BOOKINGS.b8,
        author_id: USERS.sophie,
        target_id: USERS.marc,
        role: 'PASSENGER_REVIEWING_DRIVER',
        rating: 4,
        comment: 'Bon trajet, un peu de retard au départ mais Marc nous a prévenus.',
        created_at: DateTime.now().minus({ weeks: 6 }).toSQL(),
      },
      // Marc note Sophie
      {
        id: randomUUID(),
        booking_id: BOOKINGS.b8,
        author_id: USERS.marc,
        target_id: USERS.sophie,
        role: 'DRIVER_REVIEWING_PASSENGER',
        rating: 4,
        comment: 'Sympa et facile à prendre en route.',
        created_at: DateTime.now().minus({ weeks: 6 }).toSQL(),
      },
    ])
  }
}
