/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Alerts: () => import('#controllers/alerts_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Bookings: () => import('#controllers/bookings_controller'),
  Events: () => import('#controllers/events_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Reviews: () => import('#controllers/reviews_controller'),
  Rides: () => import('#controllers/rides_controller'),
  TicketmasterAdmin: () => import('#controllers/ticketmaster_admin_controller'),
  Users: () => import('#controllers/users_controller'),
}
